---
- name: Installation von Nutanix-Tols
  hosts: all
  become: yes  # Erlaube sudo-Berechtigungen

  tasks:
    - name: Kopiere den gesamten Ordner
      synchronize:
        src: "/home/lxadmin/nutanixtools/"
        dest: "/home/lxadmin/"

    - name: Führe das Setup-Skript mit Python 3 aus
      command: python3 /home/lxadmin/nutanixtools/installer/linux/install_ngt.py

    - name: Lösche den Installationsordner
      file:
        path: "/home/lxadmin/nutanixtools"
        state: absen
