- name: Synchronisieren des Ordners auf entfernte Maschinen, Skript ausführen und danach Ordner löschen
  hosts: all
  tasks:
    - name: Synchronisieren des Ordners 'nutanixtools'
      synchronize:
        src: /tmp/nutanixtools/
        dest: /tmp/nutanixtools/
        recursive: yes

    - name: Ausführen des Python-Skripts 'install_ngt.py'
      command: python3 /tmp/nutanixtools/installer/linux/install_ngt.py

    - name: Löschen des Ordners 'nutanixtools' auf den entfernten Maschinen
      file:
        path: /tmp/nutanixtools/
        state: absent
